feat: changesets docs
getnacelle/nacelle-js pull request #198
Opened 2022-08-01 18:27 UTC by KrisQ

### WHY are these changes introduced?

Fixes [[ENG-6345](https://nacelle.atlassian.net/browse/ENG-6345)] 

### WHAT is this pull request doing?

Adds changesets docs to CONTRIBUTING.md

2022-08-01 19:06 UTC, alexcasche commented on CONTRIBUTING.md
> +Versioning is handled by [Changesets](https://github.com/changesets/changesets). Packages contributors are expected to add changeset by running `npm run changesets` on the root and chose the appropri
```suggestion
Versioning is handled by [Changesets](https://github.com/changesets/changesets). Packages contributors are expected to add a changeset by running `npm run changesets` in the project's root, choose the appropriate bump and write some markdowns which will be added to the changelogs.
```

2022-08-01 19:08 UTC, alexcasche requested changes
Looks good.  One minor nitpick

2022-08-02 13:35 UTC, KrisQ commented
Thanks for correcting the grammar @alexcasche , should be all good now!

2022-08-02 13:37 UTC, alexcasche approved these changes

2022-08-02 13:38 UTC, merged