feat: shopify-cart in nuxt starter
getnacelle/nacelle-js pull request #249
Opened 2022-09-20 15:00 UTC by KrisQ

### WHY are these changes introduced?

Fixes [[ENG-7070](https://nacelle.atlassian.net/browse/ENG-7070)] 

### WHAT is this pull request doing?

Adds shopify cart to the nuxt starter
Replace checkout with shopify cart checkout

### How to Test

- `git checkout ENG-7070--nuxt-starter-shopify-cart`
- to the nuxt reference store project `.env` add the following: (reach out if you want the vars I used)

```
SHOPIFY_SHOP_ID="<YOUR_SHOPIFY_ID>"
SHOPIFY_STOREFRONT_ACCESS_TOKEN="<YOUR_SHOPIFY_STOREFRONT_ACCESS_TOKEN>"
```

- `cd starter/nuxt`
- `npm i && npm run generate && npm run start`
- see if cart/checkout works

2022-09-21 15:11 UTC, alexcasche requested changes
Just some initial console logs to cleanup.  About to do actual testing locally

2022-09-21 15:11 UTC, alexcasche commented on starters/nuxt/pages/index.vue
> +    console.log('HELLO2', this.$cartClient);
Can we remove this?

2022-09-21 15:11 UTC, alexcasche commented on starters/nuxt/pages/products/_handle.vue
> +      console.log('A', this.quantity);
Remove console log

2022-09-21 15:28 UTC, alexcasche commented
Seeing a bug when trying to increment the quantity of a line item.  See attached.  _Could_ be unrelated to your PR but wanted to flag.  It is saying that the merchandiseID is not valid in Shopify.  But for incrementing, no merchandiseId should be necessary

https://user-images.githubusercontent.com/24395931/191546218-10c7d743-54f0-4c62-abb4-ecac1d0a5782.mov

<img width="674" alt="Screen Shot 2022-09-21 at 11 27 23 AM" src="https://user-images.githubusercontent.com/24395931/191546233-28714c39-484b-4826-be37-9c18b0db9064.png">

2022-09-21 15:38 UTC, KrisQ commented
> Seeing a bug when trying to increment the quantity of a line item. See attached. _Could_ be unrelated to your PR but wanted to flag. It is saying that the merchandiseId is not valid in Shopify. But for incrementing, no merchandiseId should be necessary
> 
>  Screen.Recording.2022-09-21.at.11.18.46.AM.mov 
> <img alt="Screen Shot 2022-09-21 at 11 27 23 AM" width="674" src="https://user-images.githubusercontent.com/24395931/191546233-28714c39-484b-4826-be37-9c18b0db9064.png">
> 
> Think you just need to remove the `nacelleEntryId` from this action <img alt="Screen Shot 2022-09-21 at 11 32 29 AM" width="472" src="https://user-images.githubusercontent.com/24395931/191547446-fe3f440d-310c-450a-89a8-35812433f470.png">

Hey @alexcasche isn't this a bug in the package that will be resolved once we find a solution for `nacelleEntryId`, it works locally for me but I think I have a temporary workaround in my build for that bug in `shopify-cart`

2022-09-22 14:39 UTC, NWRichmond requested changes
This seems mostly complete, but there are some issues.

Other than the issues described in the comments below, the `/cart` experience isn't quite right. When adding an item to the cart from a PDP and navigating to `/cart`, the cart appears empty at first, and doesn't indicate that it's in a loading state:

https://user-images.githubusercontent.com/5732000/191775816-1a611fbf-4e20-4821-80f2-12a907a0b2d9.mov

One way to avoid hard-loading `/cart` in the first place would be to add a
```vue
<nuxt-link to="/cart">View Cart</nuxt-link>
```
to the PDP:

https://user-images.githubusercontent.com/5732000/191776334-dd180b16-7761-410f-93c4-cd654fdc4138.mov

This might be sufficient. If there's a way to simply implement a loading state on the `/cart` page ("Loading Cart..."), then that might be good too, especially when refreshing the `/cart` page.

Lastly, while not related to this PR, let's take this opportunity to use consistent casing in the `buttonText` in `starters/nuxt/pages/products/_handle.vue`. Instead of `'Add To cart'`, let's use `'Add to Cart'`.

2022-09-22 14:39 UTC, NWRichmond commented on starters/nuxt/pages/cart.vue
> +          <pre>{{ JSON.stringify(lineItem, null, 2) }}</pre>
This needs to be removed

```suggestion
```

<img width="800" alt="cart page pre with line item json" src="https://user-images.githubusercontent.com/5732000/191772686-6fbc7fd4-ab55-4b28-bef1-095596a358a8.png">

2022-09-22 14:39 UTC, NWRichmond commented on starters/nuxt/package.json
> +    "@nacelle/shopify-cart": "^0.2.1",
1. `@nacelle/shopify-checkout` should be removed.
2. We need the `package-lock.json` updated. Try `npm i --package-lock.json` and bootstrapping again to make sure everything is in sync.

2022-09-22 14:39 UTC, NWRichmond commented on starters/nuxt/pages/products/_handle.vue
> +          quantity: parseInt(this.quantity)
Why `parseInt`? Looks like `this.quantity` is already an integer:

<img width="600" alt="product page this quantity number" src="https://user-images.githubusercontent.com/5732000/191774238-5fce7289-30b6-41bc-907b-e31b5cdd62d4.png">

2022-09-22 18:45 UTC, NWRichmond approved these changes
Awesome! Thanks so much for those updates, @KrisQ.

https://user-images.githubusercontent.com/5732000/191826850-6ae579b7-2e2b-49ca-9491-f578e91dcec9.mov

2022-09-22 19:00 UTC, merged